/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospitalosconvert;

import com.hospital_os.object.Patient;
import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;

/**
 *
 * @author ekapop
 */
public class NewJFrame extends javax.swing.JFrame {
    Patient thePatient;
    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
        this.setSize(400, 400);
        this.setLocationRelativeTo(null); 
    }
    private void getPatient(Patient thePatient)
    {
        thePatient.hn="";
        thePatient.couple_id = "";
        thePatient.father_pid = "";
        thePatient.mother_pid = "";
        thePatient.patient_birthday = "";
        thePatient.ampur = "";
        thePatient.changwat = "";
        thePatient.tambon =  "";
        thePatient.blood_group_id = "1";
        thePatient.education_type_id = "11";
        thePatient.status_id =  "2";
        thePatient.f_sex_id =  "1";
        thePatient.labor =  "1";
        thePatient.marriage_status_id = "1";
        thePatient.nation_id =  "99";
        thePatient.occupation_id =  "000";
        thePatient.f_prefix_id =  "000";
        thePatient.race_id =  "99";
        thePatient.religion_id =  "1";
//        thePatient.typearea =  "1";
        thePatient.couple_firstname =  "";
        thePatient.couple_lastname =  "";
        thePatient.father_firstname =  "";
        thePatient.father_lastname =  "";
        thePatient.patient_name =  "";
        thePatient.house =  "";
        thePatient.patient_last_name =  "";
        thePatient.mother_firstname =  "";
        thePatient.mother_lastname =  "";
        thePatient.private_doc =  "";
        thePatient.p_type =  "";
        thePatient.road =  "";
        thePatient.village =  "";
        thePatient.pid =  "";
        thePatient.phone =  "";
        thePatient.relation =  "00";
        thePatient.sex_contact =  "1";
        thePatient.house_contact =  "";
        thePatient.village_contact =  "";
        thePatient.road_contact =  "";
        thePatient.phone_contact =  "";
        thePatient.ampur_contact = "";
        thePatient.changwat_contact = "";
        thePatient.tambon_contact =  "";
        thePatient.xn =  "";
        thePatient.pid =  "";
        thePatient.contact_fname =  "";
        thePatient.contact_lname =  "";
        thePatient.patient_birthday_true = "0";
        thePatient.record_date_time =  "";
        thePatient.staff_record = "";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jButtonOpenFile = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jButtonConvert = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jButtonOpenFile.setText("open file");
        jButtonOpenFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOpenFileActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        getContentPane().add(jButtonOpenFile, gridBagConstraints);

        jPanel1.setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 180, 0);
        getContentPane().add(jPanel1, gridBagConstraints);

        jButtonConvert.setText("Convert");
        jButtonConvert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConvertActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        getContentPane().add(jButtonConvert, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonOpenFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOpenFileActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setCurrentDirectory(new File(System.getProperty("user.home")));
        int result = fileChooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            System.out.println("Selected file: " + selectedFile.getAbsolutePath());
        }
    }//GEN-LAST:event_jButtonOpenFileActionPerformed

    private void jButtonConvertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConvertActionPerformed
        try {
            // TODO add your handling code here:
            String userDB="sa",passDB="Ekartc2c5", hostDB="DESKTOP-H18GJTN";
            String sql = "Select * FROM users";
            Class.forName( "com.microsoft.sqlserver.jdbc.SQLServerDriver" );
            Connection con = DriverManager.getConnection( "jdbc:sqlserver://"+hostDB+":1433;databasename=bithis", userDB, passDB );
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery(sql);
            while (rs.next()) {
//                dbtime = rs.getString(1);
//                System.out.println(dbtime);
            } //end while

            con.close();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButtonConvertActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonConvert;
    private javax.swing.JButton jButtonOpenFile;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
